# R Programming — Week 3 Notes
### Basics of Calculations, Built-in Functions, and Matrices

## Vector Addition
Arithmetic operators like `+` work **element-wise** on vectors created with `c()`.

In [1]:
c(2, 3, 5, 7) + c(-2, -3, -5, 8)

[1]  0  0  0 15

## Power Operator
`^` and `**` both raise a number to a power.

In [2]:
2^3
2**3

[1] 8

[1] 8

## Power Operator with Negative and Fractional Exponents
Fractional exponents give roots, negative exponents give reciprocals.

In [3]:
2^0.5
2**0.5
2^-0.5

[1] 1.414214

[1] 1.414214

[1] 0.7071068

## Power Operator Applied to a Vector (Scalar Exponent)
When a vector is raised to a scalar power, the power is applied to every element.

In [4]:
c(2, 3, 5, 7)^2

[1]  4  9 25 49

## Power Operator with Two Equal-Length Vectors
When both base and exponent are vectors of the same length, the operation is element-wise, pairing corresponding elements.

In [5]:
c(2, 3, 5, 7)^c(2, 3)

[1]   4  27  25 343

## Power Operator with Recycling
If the exponent vector is shorter, it is **recycled** to match the length of the base vector.

In [6]:
c(1, 2, 3, 4, 5, 6)^c(2, 3, 4)

[1]    1    8   81   16  125 1296

## Power Operator — Recycling Warning
If the shorter vector's length does not evenly divide the longer vector's length, R still recycles but issues a warning.

In [7]:
c(2, 3, 5, 7)^c(2, 3, 4)

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

## Integer Division with a Scalar
Operator `%/%` performs division and discards the fractional remainder.

In [8]:
2 %/% 2
5 %/% 2
7 %/% 3

[1] 1

[1] 2

[1] 2

## Integer Division on a Vector
The `%/%` operator applies to each element of a vector against a scalar.

In [9]:
c(2, 3, 5, 7) %/% 2

[1] 1 1 2 3

## Integer Division with Two Vectors
With equal-length vectors, elements are paired and divided one-to-one.

In [10]:
c(2, 3, 5, 7) %/% c(2, 3)

[1] 1 1 2 2

## Integer Division with Recycling Warning
When lengths are unequal and not multiples, R recycles the shorter vector and warns about it.

In [11]:
c(2, 3, 5) %/% c(2, 3)

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

## Modulo Division with Scalars
Operator `%%` returns the remainder after division (x mod y).

In [12]:
2 %% 2
3 %% 2
7 %% 3
7 %% 4

[1] 0

[1] 1

[1] 1

[1] 3

## Modulo Division on a Vector
`%%` applied element-wise to a vector against a scalar.

In [13]:
c(2, 3, 5, 7) %% 2

[1] 0 1 1 1

## Modulo Division with Two Vectors
Equal-length vectors pair elements for the modulo operation.

In [14]:
c(2, 3, 5, 7) %% c(2, 3)

[1] 0 0 1 1

## Modulo Division with Recycling Warning
Unequal, non-multiple lengths trigger a recycling warning.

In [15]:
c(2, 3, 5) %% c(2, 3)

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

## Maximum
`max()` returns the largest value. Note: passing values directly vs. wrapping them in `c()` can behave differently in older R versions.

In [16]:
max(1.2, 3.4, -7.8)
max(c(1.2, 3.4, -7.8))

[1] 3.4

[1] 3.4

## Minimum
`min()` returns the smallest value among its arguments.

In [17]:
min(1.2, 3.4, -7.8)
min(c(1.2, 3.4, -7.8))

[1] -7.8

[1] -7.8

## Arithmetic Mean
`mean()` computes the average. Always pass multiple values as a single vector using `c()` for correct results.

In [18]:
mean(2, 3, 4)
mean(c(2, 3, 4))

[1] 2

[1] 3

## Absolute Value
`abs()` returns the non-negative magnitude of each element.

In [19]:
abs(-4)
abs(c(-1, -2, -3, 4, 5))

[1] 4

[1] 1 2 3 4 5

## Square Root
`sqrt()` computes the square root of each element.

In [20]:
sqrt(4)
sqrt(c(4, 9, 16, 25))

[1] 2

[1] 2 3 4 5

## Sum and Product
`sum()` adds all elements; `prod()` multiplies all elements.

In [21]:
sum(c(2, 3, 5, 7))
prod(c(2, 3, 5, 7))

[1] 17

[1] 210

## Rounding
`round()` rounds a value to the nearest integer (or specified decimal places).

In [22]:
round(1.23)
round(1.83)

[1] 1

[1] 2

## Natural Logarithm
`log()` computes the natural log (base e) by default.

In [23]:
log(10)
log(exp(1))
log(c(10, 100, 1000))

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

## Logarithm Base 10
`log10()` computes the log with base 10.

In [24]:
log10(10)
log10(100)
log10(c(10, 100, 1000))

[1] 1

[1] 2

[1] 1 2 3

## Assignments
The `=` (or `<-`) operator stores a value or expression result in a variable for later use.

In [25]:
x1 = c(1, 2, 3, 4)
x1

x2 = x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

## Combining Scalars, Vectors, and Functions
Expressions can freely mix vectors, scalars, and built-in functions.

In [26]:
c(1, 2, 3, 4) + sum(c(1, 2, 3, 4)) * prod(c(1, 2))

abs(c(1, 2, 3, 4) - sum(c(1, 2, 3, 4)) * prod(c(1, 2)))

[1] 21 22 23 24

[1] 19 18 17 16

## Creating a Matrix (Column-wise)
`matrix(nrow, ncol, data)` builds a matrix, filling values column by column by default.

In [27]:
x = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8))
x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

## Accessing a Matrix Element
Use `x[i, j]` to access the element in row `i`, column `j`.

In [28]:
x[3, 2]

[1] 7

## Filling a Matrix Row-wise
Setting `byrow = TRUE` fills the matrix row by row instead of column by column.

In [29]:
y = matrix(nrow = 4, ncol = 2, data = c(1, 2, 3, 4, 5, 6, 7, 8), byrow = TRUE)
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

## Matrix Properties
`dim()`, `nrow()`, and `ncol()` return the matrix dimensions.

In [30]:
dim(x)
nrow(x)
ncol(x)

[1] 4 2

[1] 4

[1] 2

## Matrix Mode and Attributes
`mode()` shows the storage type; `attributes()` lists all attributes such as dimensions.

In [31]:
mode(x)
attributes(x)

[1] "numeric"

$dim
[1] 4 2