# Foundations of R Software: Strings, Display and Formatting

## 1. Print and Format with `cat`

`print()` outputs only one object at a time. `cat()` converts its arguments to character vectors, joins them in sequence, and writes a continuous output.

```r
cat(..., file = "", sep = " ", fill = FALSE, labels = NULL, append = FALSE)
```

- `sep`: string placed between items (default is a single space).
- `fill`: if `TRUE` or a positive number, output is broken into lines of that width.
- `labels`: character vector of labels for the lines printed when `fill` is used.
- `append`: used only when `file` is a file name; `TRUE` appends instead of overwriting.
- `cat` does not add a newline; use `"\n"` to end a line.

### print with Multiple Items (Error)

In [1]:
tryCatch(
    print("The zero occurs at", 2*pi, "radians."),
    error = function(e) cat("Error:", conditionMessage(e), "\n")
)

Error: invalid 'quote' argument

### print One Item at a Time

In [2]:
print("The zero occurs at")
print(2*pi)
print("radians")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"

### cat with Multiple Items

In [3]:
cat("The zero occurs at", 2*pi, "radians.", "\n")

The zero occurs at 6.283185 radians.

### cat with date()

In [4]:
d = date()
cat("Today's date is:", d, "\n")

Today's date is: Sun Oct  4 13:19:51 2026

### cat with sep

In [5]:
x = 1:10
x
cat(x, sep = " ++ ")
cat("\n")
cat(x, sep = " / ")
cat("\n")

 [1]  1  2  3  4  5  6  7  8  9 10

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

### cat with Expressions

In [6]:
x = 7
cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

### cat with format

In [7]:
x = 7
cat("The square root of", x, "is approximately", format(sqrt(x), digits = 3), "\n")

The square root of 7 is approximately 2.65

### cat with a Vector

In [8]:
evenno = c(2, 4, 6, 8, 10)
evenno
cat("The first few even numbers are:", evenno, "...\n")

[1]  2  4  6  8 10

The first few even numbers are: 2 4 6 8 10 ...

### cat with fill and labels

In [9]:
x = 1:10
cat(x, fill = 2, labels = paste("(", letters[1:10], "):"))

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

## 2. The `paste` Function

`paste()` converts its arguments to character strings (via `as.character`) and joins them. Unlike `cat`, the result can be assigned to a variable.

```r
paste(..., sep = " ", collapse = NULL)
paste0(..., collapse = NULL)
```

- `sep`: separator placed between the joined strings (default is a space).
- `collapse`: if given, all results are joined into a single string using this separator.
- `paste0` is `paste` with `sep = ""`.
- Vector arguments are joined element by element; shorter vectors are recycled.

### paste vs as.character

In [10]:
paste(1:12)
as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

### paste with sep

In [11]:
paste("Everybody", "loves", "R Programming.")
paste("Everybody", "loves", "R Programming.", sep = "*")
paste("Everybody", "loves", "R Programming.", sep = "===")

[1] "Everybody loves R Programming."

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

### paste with a Vector of Strings

In [12]:
names = c("Prof. Singh", "Mr.  Venkat", "Dr. Jha")
names
paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr.  Venkat" "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr.  Venkat is a good person."
[3] "Dr. Jha is a good person."

### paste with collapse

In [13]:
names = c("Prof. Singh", "Mr.  Venkat", "Dr. Jha")
paste(names, "is", "a good", "person.", collapse = ", and ")

[1] "Prof. Singh is a good person., and Mr.  Venkat is a good person., and Dr. Jha is a good person."

### Role of Blank Space inside Quotes

In [14]:
paste(1, " is first", 2, " is second", 3, " is third", sep = "#")
paste(1, " is first    ", 2, " is second      ", 3, " is third    ", sep = "#")

[1] "1# is first#2# is second#3# is third"

[1] "1# is first    #2# is second      #3# is third    "

### Generate Labels with paste

In [15]:
x = paste("Ex", 1:5, sep = "_")
x
x[1]
x[2]
x[3]
x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_5"

### paste with collapse to a Single String

In [16]:
x = paste("Ex", 1:5, sep = "_", collapse = "")
x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

### Difference between sep and collapse

In [17]:
x = paste("Ex", 1:5, sep = "_")
x
x = paste("Ex", 1:5, sep = "_", collapse = "")
x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

### paste0 and paste with a Single Vector

In [18]:
paste0(1:10)
paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

### paste0 and paste with Multiple Vectors

In [19]:
paste0(1:10, c("st", "nd", "rd", rep("th", 7)))
paste(1:10, c("st", "nd", "rd", rep("th", 7)))

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

 [1] "1 st"  "2 nd"  "3 rd"  "4 th"  "5 th"  "6 th"  "7 th"  "8 th"  "9 th"
[10] "10 th"

## 3. String Splitting with `strsplit`

`strsplit()` splits each element of a character vector into substrings. It returns a list with one element per input string.

```r
strsplit(x, split, fixed = FALSE, ...)
```

- `x`: character vector to split.
- `split`: character vector of regular expressions (or exact strings if `fixed = TRUE`) used for splitting.
- `fixed`: if `TRUE`, `split` is matched exactly; otherwise it is treated as a regular expression.
- `split = ""` splits a string into individual characters.
- Components are accessed as `result[[i]][j]`.

### Split at a Single Character

In [20]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
x
strsplit(x, split = "!")

[1] "The&!syntax&!of&!paste&!is!&available! &inthe online-help"

[[1]]
[1] "The&"                "syntax&"             "of&"
[4] "paste&"              "is"                  "&available"
[7] " &inthe online-help"

### Split at a Character String

In [21]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
strsplit(x, split = "&!")

[[1]]
[1] "The"                               "syntax"
[3] "of"                                "paste"
[5] "is!&available! &inthe online-help"

### Access Components of the Result

In [22]:
x = "The&!syntax&!of&!paste&!is!&available! &inthe online-help"
y = strsplit(x, split = "!&")
y
y[[1]][1]
y[[1]][2]
y[[1]][3]

[[1]]
[1] "The&!syntax&!of&!paste&!is"    "available! &inthe online-help"

[1] "The&!syntax&!of&!paste&!is"

[1] "available! &inthe online-help"

[1] NA

### Split Dates

In [23]:
dates = c("2020-07-24", "2021-08-25", "2022-09-26", "2023-10-27")
dates
datesplt = strsplit(dates, "-")
datesplt

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

### Convert Split Dates to a Character Matrix

In [24]:
datemat = matrix(unlist(datesplt), nrow = 4, ncol = 3, byrow = TRUE)
datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

### Convert Split Dates to a Numeric Matrix

In [25]:
datematrix = matrix(as.numeric(unlist(datesplt)), nrow = 4, ncol = 3, byrow = TRUE)
datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

### Split a String into Characters

In [26]:
strsplit("Shalabh", split = "")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

## 4. Counting Characters with `nchar` and `nzchar`

```r
nchar(x, type = "chars", allowNA = FALSE, keepNA = NA)
nzchar(x, keepNA = FALSE)
```

- `nchar` returns the number of characters in each element of `x`; non-character input is coerced to character.
- `type`: one of `"bytes"`, `"chars"`, `"width"`.
- `nzchar` returns `TRUE` for non-empty strings and `FALSE` for empty strings `""`.

### nchar on Strings

In [27]:
x = "R course 24.07.2022"
y = "Number of participants: 25"
x
y
nchar(x)
nchar(y)

[1] "R course 24.07.2022"

[1] "Number of participants: 25"

[1] 19

[1] 26

### nzchar on Strings

In [28]:
x = "R course 24.07.2022"
y = "Number of participants: 25"
nzchar(x)
nzchar(y)

[1] TRUE

[1] TRUE

### nzchar on Vectors

In [29]:
x = c("Apple", "Banana", "Cake")
x
nzchar(x)
y = c("Apple", "", "Cake")
y
nzchar(y)

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

### nchar on Character and Numeric Vectors

In [30]:
x = c("Apple", "Banana", "Cake")
nchar(x)
y = c(2, 4, 6)
nchar(y)
z = c(11, 222, 3333)
nchar(z)
z1 = c(1.1, 2.22, 3.333)
nchar(z1)

[1] 5 6 4

[1] 1 1 1

[1] 2 3 4

[1] 3 4 5

## 5. Lower and Upper Case with `tolower` and `toupper`

```r
tolower(x)
toupper(x)
```

- `tolower` converts upper-case characters to lower case.
- `toupper` converts lower-case characters to upper case.
- Non-alphabetic characters are left unchanged.

### toupper

In [31]:
x = "R course will start from 24.07.2022"
x
toupper(x)

[1] "R course will start from 24.07.2022"

[1] "R COURSE WILL START FROM 24.07.2022"

### tolower

In [32]:
z = "INDIAN INSTITUTE OF TECHNOLOGY"
z
tolower(z)

[1] "INDIAN INSTITUTE OF TECHNOLOGY"

[1] "indian institute of technology"