# R Programming — Week 5: Missing Data & Conditional Execution

Notes converted into a runnable Colab notebook. Switch the Colab runtime to **R** (Runtime > Change runtime type > R) before executing.

## 1. Detecting Missing Values with `is.na()`

R stores missing observations as `NA`. `is.na(x)` returns a logical vector, `TRUE` wherever a value is missing.

In [1]:
x = NA
is.na(x)

[1] TRUE

## 2. `is.na()` on a Vector

`is.na()` works on vectors, lists, matrices, and data frames, returning one `TRUE`/`FALSE` per element.

In [2]:
x = c(11, NA, 13, NA)
is.na(x)

[1] FALSE  TRUE FALSE  TRUE

## 3. Handling `NA` in `mean()`

Arithmetic functions like `mean()` return `NA` if any input is missing. Setting `na.rm = TRUE` drops the missing values before computing.

In [3]:
x = c(11, NA, 13, NA)
mean(x)
mean(x, na.rm = TRUE)

[1] NA

[1] 12

## 4. `NA` versus `NULL`

`NA` is a placeholder for a value that exists but is missing. `NULL` represents something that never existed at all; it is returned by some functions and expressions.

## 5. Locating Missing Values with `which()`

`which(is.na(x))` returns the index positions where `x` is `NA`.

In [4]:
x = c(11, NA, 13, NA)
x
which(is.na(x))

[1] 11 NA 13 NA

[1] 2 4

## 6. Counting Missing Values with `sum()`

Since `TRUE`/`FALSE` are treated as `1`/`0`, `sum(is.na(x))` counts how many values are missing.

In [5]:
x = c(11, NA, 13, NA)
x
sum(is.na(x))

[1] 11 NA 13 NA

[1] 2

## 7. Finding Complete Cases

`complete.cases(x)` returns a logical vector marking the positions that are **not** missing.

In [6]:
x = c(11, NA, 13, NA)
x
complete.cases(x)

[1] 11 NA 13 NA

[1]  TRUE FALSE  TRUE FALSE

## 8. Removing Missing Values with `na.omit()`

`na.omit(x)` returns the object with missing values deleted listwise, permanently dropping any row/element that contains `NA`.

In [7]:
x = c(11, NA, 13, NA)
x
y = na.omit(x)
y
mean(x)
mean(y)

[1] 11 NA 13 NA

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] NA

[1] 12

## 9. Conditional Execution: `if()`

```
if (condition) {
    execute commands if condition is TRUE
}
```
The code inside `{}` runs only when the condition is `TRUE`; if it is `FALSE`, R silently skips it and gives no output. `if()` should only be used with a single-element (scalar) condition, not a vector.

In [8]:
x = 5
if (x > 4) x * 3

x = 3
if (x > 4) x * 3

[1] 15

### Same Example Using `{}`

In [9]:
x = 5
if (x > 4) {
    x * 3
}

x = 3
if (x > 4) {
    x * 3
}

[1] 15

### Printing a Message Conditionally

In [10]:
x = 6
if (x > 3) {
    print("The value is more than 3")
}

[1] "The value is more than 3"

In [11]:
x = 2
if (x > 3) {
    print("The value is more than 3")
}

## 10. Conditional Execution: `if...else()`

```
if (condition) {
    executes commands if condition is TRUE
} else {
    executes commands if condition is FALSE
}
```
The condition should be a single value, not a vector, and may combine expressions using `&&` (and) or `||` (or).

In [12]:
x = 5
if (x == 3) {
    x = x - 1
} else {
    x = 2 * x
}
x

[1] 10

In [13]:
x = 3
if (x == 3) {
    x = x - 1
} else {
    x = 2 * x
}
x

[1] 2

### Printing Which Branch Was Taken

In [14]:
x = 6
if (x > 3) {
    print("The value is more than 3")
} else {
    print("The value is less than 3")
}

[1] "The value is more than 3"

In [15]:
x = 2
if (x > 3) {
    print("The value is more than 3")
} else {
    print("The value is less than 3")
}

[1] "The value is less than 3"

## 11. Nested `if...else...if`

When there are more than two alternatives, chain `else if` blocks:
```
if (condition1) {
    ...
} else if (condition2) {
    ...
} else if (condition3) {
    ...
} else {
    executes commands if all conditions are FALSE
}
```

In [16]:
x = 5
if (x == 3) {
    x = x - 1
} else if (x < 3) {
    x = x + 5
} else {
    x = 2 * x
}
x

[1] 10

In [17]:
x = 2
if (x == 3) {
    x = x - 1
} else if (x < 3) {
    x = x + 5
} else {
    x = 2 * x
}
x

[1] 7

In [18]:
x = 3
if (x == 3) {
    x = x - 1
} else if (x < 3) {
    x = x + 5
} else {
    x = 2 * x
}
x

[1] 2

## 12. Vectorized Conditional: `ifelse()`

```
ifelse(test, yes, no)
```
Unlike `if()`, `ifelse()` evaluates a condition element-by-element over an entire vector, returning `yes` where the test is `TRUE` and `no` where it is `FALSE`.

In [19]:
x = 1:10
x
ifelse(x < 6, x^2, x + 1)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  4  9 16 25  7  8  9 10 11

### Odd/Even Example (Modulo `%%`)

`%%` gives the remainder of division. A remainder of `0` when dividing by `2` means the number is even.

In [20]:
x = c(7, 9, 8, 4)
ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

## 13. `switch()` for Multiway Branching

```
switch(expr, ...)
```
`switch` compares `expr` against a list of cases and returns the matching value. A numeric `expr` selects the corresponding position; a character `expr` is matched against named arguments. If there is no match and no unnamed fallback element, `switch` returns nothing.

In [21]:
switch(2, "apple", "banana", "orange")
switch(1, "apple", "banana", "orange")

[1] "banana"

[1] "apple"

### Matching by Name

In [22]:
switch("colour", colour = "blue", gender = "male", volume = 50)
switch("volume", colour = "blue", gender = "male", volume = 50)

[1] "blue"

[1] 50

### No Match Case

In [23]:
switch(4, "apple", "banana", "orange")
switch("size", colour = "blue", gender = "male", volume = 50)

## 14. `which()` for Positions Satisfying a Condition

```
which(x, arr.ind, useNames)
```
`which()` returns the indices of a logical vector that are `TRUE`. With `arr.ind = TRUE` on a matrix, it returns row/column positions instead of flat indices.

In [24]:
x = c(10, 15, 8, 14, 6, 12)
x
which(x == 14)
which(x != 12)
which(x > 10)

[1] 10 15  8 14  6 12

[1] 4

[1] 1 2 3 4 5

[1] 2 4 6

### `which.min()` and `which.max()`

In [25]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
x
which.min(x)
which.max(x)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1

[1] 9

### `which()` with `arr.ind = TRUE` on a Matrix

In [26]:
x = matrix(nrow = 3, ncol = 3, data = 1:9)
x
which(x %% 2 == 1)
which(x %% 2 == 1, arr.ind = TRUE)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3