##More sequences and other operations

## 1. Colon Operator `:`
The colon operator `a:b` generates a sequence with a constant increment of 1 (or -1 if `a > b`). It also works with decimals and negative numbers.

In [1]:
1:10
10:1
5:15
15:5

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 10  9  8  7  6  5  4  3  2  1

 [1]  5  6  7  8  9 10 11 12 13 14 15

 [1] 15 14 13 12 11 10  9  8  7  6  5

In [2]:
-1:-10
-10:-1
-5:-15
-15:-5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

In [3]:
1.23:10
1.23:10.54
10.54:2.23

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

## 2. The `seq()` Function
`seq(from, to, by, length.out, along.with)` generates regular sequences. `seq(10)` is same as `1:10`.

In [4]:
seq(10)
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

## 3. `seq()` with Predefined Variable and Increment
The `by` argument can be an expression, e.g. `x/10`, to control the step size.

In [5]:
x=2
seq(1,x,x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [6]:
x=50
seq(0,x,x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

## 4. Storing Sequence Output
The output of `seq()` can be assigned to a variable and reused in further computations.

In [8]:
x=seq(1,50,1/2)
x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

In [9]:
y=2*x
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

## 5. Index Vectors
`seq(along = x)` creates an index vector matching the length of `x`. Elements of `x` can then be accessed using this index vector.

In [10]:
x=c(9,8,7,6)
ind = seq(along=x)
ind

[1] 1 2 3 4

In [11]:
x[ind[2]]

[1] 8

## 6. Sys.time() and Sys.Date()
`Sys.time()` returns the current date and time; `Sys.Date()` returns only the current date, from the system clock.

In [14]:
Sys.time()

[1] "2026-09-03 08:56:49 UTC"

In [15]:
Sys.Date()

[1] "2026-09-03"

## 7. Sequences of Dates
`seq(from, to, by, length.out)` also works on `Date` objects. The `by` argument accepts `"day"`, `"week"`, `"month"`, `"quarter"`, or `"year"`.

In [16]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by="years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

In [22]:
seq(as.Date("2017-01-01"), by="days", length=6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

In [20]:
seq(as.Date("2017-01-01"), by="months", length=6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

In [21]:
seq(as.Date("2017-01-01"), by="years", length=6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

### Sequence Between Two Dates (Reverse / Negative Step)
Using a negative `by` value like `"-1 month"` generates the sequence from the end date back to the start date.

In [27]:
startdate = as.Date("2016-01-01")
enddate = as.Date("2017-01-01")
output = seq(enddate, startdate, by = "-1 month")
output
output = seq(startdate, enddate, by="month")
output

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

 [1] "2016-01-01" "2016-02-01" "2016-03-01" "2016-04-01" "2016-05-01"
 [6] "2016-06-01" "2016-07-01" "2016-08-01" "2016-09-01" "2016-10-01"
[11] "2016-11-01" "2016-12-01" "2017-01-01"

## 8. Sequence of Alphabets
`letters` gives the sequence of lowercase alphabets and `LETTERS` gives uppercase alphabets. Indexing `letters[from:to]` extracts a subrange.

In [28]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

In [30]:
letters[1:3]
letters[3:1]
letters[17:20]
letters[2]

[1] "a" "b" "c"

[1] "c" "b" "a"

[1] "q" "r" "s" "t"

[1] "b"

In [31]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

In [32]:
LETTERS[1:4]
LETTERS[5:1]
LETTERS[17:20]
LETTERS[20:17]
LETTERS[2]

[1] "A" "B" "C" "D"

[1] "E" "D" "C" "B" "A"

[1] "Q" "R" "S" "T"

[1] "T" "S" "R" "Q"

[1] "B"

## 9. Repeats — `rep()`
`rep(x, times = n)` repeats the entire vector `x`, `n` times. `rep(x, each = n)` repeats each element `n` times before moving to the next.

In [34]:
rep(3.5, times=10)
rep(1:4, 2)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 2 3 4 1 2 3 4

In [37]:
x=1:4
x
rep(x, times=3)
rep(x, each=3)

[1] 1 2 3 4

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

### Combining `each` and `times`
When both arguments are used together, the order in which they are specified affects the resulting sequence.

In [38]:
rep(1:4, each=2)
rep(1:4, each=2, times=3)
rep(1:4, times=3, each=2)    #regardless of order each is first

[1] 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

### Repeating Each Element a Different Number of Times
If the second argument to `rep()` is itself a vector, each element of `x` is repeated according to the corresponding value in that vector.

In [39]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [41]:
ans=seq(from=2, to=8, by=2)
ans
rep(1:4, ans)

[1] 2 4 6 8

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

### Repeating a Matrix
`rep()` applied to a matrix repeats its elements column-wise as a flat vector.

In [43]:
x=matrix(nrow=2, ncol=2, data=1:4, byrow=T) #by default its columnwise so byrow function does rowwise
x
rep(x,3) #columnwise

     [,1] [,2]
[1,] 1    2
[2,] 3    4

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

### Repetition of Character Vectors

In [62]:
rep(c("a", "b", "c"), 2)
rep(c("apple", "banana", "cake"), 2)

[1] "a" "b" "c" "a" "b" "c"

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

### Repetition for a Pre-Specified Output Length
`rep(x, length.out = n)` (or `length = n`) recycles `x` until the output has length `n`.

In [44]:
rep(2, length.out=5)
rep(2, length=5)
rep(c(2,3), length=5)
rep(c(2,3,4), length=5)

[1] 2 2 2 2 2

[1] 2 2 2 2 2

[1] 2 3 2 3 2

[1] 2 3 4 2 3

In [45]:
rep("apple", length=5)
rep(c("a","b","c"), length=5)
rep(c("a","b","c"), length=2)

[1] "apple" "apple" "apple" "apple" "apple"

[1] "a" "b" "c" "a" "b"

[1] "a" "b"

## 10. Sorting — `sort()`
`sort(x, decreasing = FALSE)` arranges the values of `x` in ascending order by default; set `decreasing = TRUE` for descending order.

In [46]:
y=c(8,5,7,6)
y
sort(y)
sort(y, decreasing = TRUE)

[1] 8 5 7 6

[1] 5 6 7 8

[1] 8 7 6 5

## 11. Ordering — `order()`
`order(x)` returns the **indices/positions** that would arrange `x` in ascending order, rather than the sorted values themselves.

In [47]:
y=c(9,8,5,7,6)
y
order(y)
order(y, decreasing=TRUE)

[1] 9 8 5 7 6

[1] 3 5 4 2 1

[1] 1 2 4 5 3

## 12. `mode()` Function
`mode()` returns how an object is stored internally, e.g. `"numeric"`, `"character"`, `"list"`, or `"function"`.

In [48]:
mode(2.432)
mode(c(3,4,5,6,7)) #mode of content is numeric
mode("India")
mode(c("India", "Australia")) #mode of vector is depend on its content here it is character

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "character"

In [51]:
mode(factor(c("UP","MP")))
mode(list("India", "USA"))
mode(data.frame(x=1:2, y=c("India", "USA")))
mode(print)

[1] "numeric"

[1] "list"

[1] "list"

[1] "function"

## 13. Lists
A list can hold elements of **different modes and types** (numbers, characters, matrices, etc.), unlike a vector where all elements must share the same mode. List elements are accessed with `[[ ]]`.

In [53]:
x1=matrix(nrow=2, ncol=2, data=1:4, byrow=T)
x2=matrix(nrow=2, ncol=2, data=5:8, byrow=T)
x1
x2
x1 + x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

### Mixing Types Breaks Numeric Operations
Assigning a character value into a numeric matrix coerces the whole matrix to character mode, so arithmetic operations then fail.

In [54]:
x1[2,1] = "hello"
x1

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

### Creating a List of Matrices

In [56]:
matlist = list(x1, x2)
matlist

[[1]]
     [,1]    [,2]
[1,] "1"     "2"
[2,] "hello" "4"

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### Single Bracket `[ ]` vs Double Bracket `[[ ]]`
`matlist[1]` returns a **sublist** (still a list), while `matlist[[1]]` returns the actual element itself.

In [57]:
matlist[1]
matlist[2]

[[1]]
     [,1]    [,2]
[1,] "1"     "2"
[2,] "hello" "4"

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### List with Mixed Object Types
A single list can hold a character vector, a numeric vector, and a matrix together.

In [58]:
z1=list(c("water", "juice", "lemonade"), rep(1:4, each=2), matrix(data=5:8, nrow=2, ncol=2, byrow=T))
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

### Extracting Elements from a List
`z1[1][2]` indexes the sublist and returns `NULL` since a sublist has only one element. `z1[[1]][2]` first extracts the actual vector, then indexes into it correctly.

In [59]:
z1[[1]]

[1] "water"    "juice"    "lemonade"

In [60]:
z1[1][2] #bcoz it considers 1d array

[[1]]
NULL

In [61]:
z1[[1]][2]

[1] "juice"