# R Programming - Matrix Operations & Logical/Relational Operators

## 1. Creating a Matrix and Renaming Row/Column Names
A matrix is built with `matrix(nrow, ncol, data)`. `rownames()` and `colnames()` label the rows and columns.

In [1]:
x = matrix(nrow = 4, ncol = 3, data = c(1:12))
x

rownames(x) = c("r1", "r2", "r3", "r4")
colnames(x) = c("c1", "c2", "c3")
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

## 2. Assigning a Specified Number to All Matrix Elements
If `data` is a single value, it is recycled to fill every cell of the matrix.

In [2]:
x = matrix(nrow = 4, ncol = 2, data = 2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

## 3. Diagonal Matrix
`diag(value, nrow, ncol)` creates a diagonal matrix with `value` on the diagonal and 0 elsewhere.

In [3]:
d = diag(1, nrow = 3, ncol = 3)
d

d = diag(5, nrow = 3, ncol = 3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

## 4. Transpose of a Matrix
`t(x)` returns the transpose X' of matrix X, swapping rows and columns.

In [4]:
x = matrix(nrow = 4, ncol = 2, data = 1:8, byrow = T)
x

xt = t(x)
xt

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

## 5. Row and Column Sums
`rowSums(x)` adds elements across each row, `colSums(x)` adds elements down each column.

In [5]:
x = matrix(nrow = 4, ncol = 2, data = c(1,2,3,4,5,6,7,8))
x

rowSums(x)
colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

## 6. Row and Column Means
`rowMeans(x)` and `colMeans(x)` compute the average of each row and column respectively.

In [6]:
x = matrix(nrow = 4, ncol = 2, data = c(1,2,3,4,5,6,7,8))
x

rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

## 7. Access to Rows, Columns or Submatrices
Use `x[row, col]` indexing. A blank index means "all". Ranges use `:` and arbitrary sets use `c()`.

In [7]:
x = matrix(nrow = 5, ncol = 3, byrow = T, data = 1:15)
x

x[3, ]
x[, 2]
x[4:5, 2:3]
x[c(1,4), c(1,3)]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

[1] 7 8 9

[1]  2  5  8 11 14

     [,1] [,2]
[1,] 11   12
[2,] 14   15

     [,1] [,2]
[1,]  1    3
[2,] 10   12

## 8. Scalar Addition, Subtraction, Multiplication and Division
Arithmetic between a matrix and a single number is applied element-wise to every entry.

In [8]:
x = matrix(nrow = 4, ncol = 2, data = 1:8, byrow = T)

x + 5
x - 5
5 * x
x / 2

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

## 9. Addition and Subtraction of Matrices
Matrices of the same dimension can be added or subtracted directly using `+` and `-`, element by element.

In [9]:
x = matrix(nrow = 4, ncol = 2, data = 1:8, byrow = T)
y = matrix(nrow = 4, ncol = 2, data = 11:18, byrow = T)

x + y
x - y

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

## 10. Multiplication of Matrices
`%*%` performs true matrix multiplication (not element-wise). Dimensions must be conformable: (n x k) %*% (k x m).

In [10]:
x = matrix(nrow = 4, ncol = 2, data = 1:8, byrow = T)
y = matrix(nrow = 2, ncol = 4, data = 11:18, byrow = T)

x %*% y
y %*% x

t(x) %*% x
x %*% t(x)

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

## 11. Cross Product
`crossprod(x)` computes X'X faster than the equivalent `t(x) %*% x`.

In [11]:
x = matrix(nrow = 4, ncol = 2, data = 1:8, byrow = T)

crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

## 12. Concatenating Matrices
`rbind(x, y)` stacks matrices row-wise; `cbind(x, y)` joins matrices column-wise.

In [12]:
x = matrix(nrow = 3, ncol = 2, data = 1:6, byrow = T)
y = matrix(nrow = 3, ncol = 2, data = 11:16, byrow = T)

rbind(x, y)
cbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

## 13. Inverse of a Matrix
`solve(y)` returns the inverse of a square, invertible (positive definite) matrix.

In [13]:
y = matrix(nrow = 2, ncol = 2, byrow = T, data = c(84,100,100,120))
y

solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

## 14. Eigenvalues and Eigenvectors
`eigen(y)` returns a list with `$values` (eigenvalues) and `$vectors` (corresponding eigenvectors) of a square matrix.

In [14]:
y = matrix(nrow = 2, ncol = 2, byrow = T, data = c(84,100,100,120))

eigen(y)

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

## 15. Relational Operators
`>`, `>=`, `<`, `<=`, `==`, `!=` compare values element-wise and return `TRUE`/`FALSE`.

In [15]:
8 > 7
7 < 5
7 >= 7
8 <= 8
8 != 9
7 == 7

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

## 16. Logical Operators: `&` vs `&&` and `|` vs `||`
`&` and `|` compare every element of a vector (element-wise). `&&` and `||` look only at the first element of each vector and stop as soon as the result is known.

In [17]:
x = c(8, 18)

(x < 10) & (x > 2)
(x[1] < 10) && (x[1] > 2)

(x < 10) | (x < 2)
(x[1] < 10) || (x[1] < 2)

[1]  TRUE FALSE

[1] TRUE

[1]  TRUE FALSE

[1] TRUE

## 17. Using Logical Vectors to Filter Data
A logical vector produced by comparisons can be used inside `x[...]` to extract only the elements that satisfy the condition.

In [18]:
x = 1:6

(x > 2) & (x < 5)
x[(x > 2) & (x < 5)]

(x > 2) | (x < 5)
x[(x > 2) | (x < 5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

## 18. Negation, xor, isTRUE and isFALSE
`!x` negates a logical value. `xor(x, y)` is TRUE only when exactly one of x, y is TRUE. `isTRUE()`/`isFALSE()` test a single logical value.

In [19]:
x = TRUE
y = FALSE

!x
xor(x, y)
isTRUE(8 > 6)
isFALSE(5 > 8)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE